name: photoapi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  logging: ^1.0.2
  equatable: ^2.0.3
  dio: ^4.0.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  bloc_test: ^9.0.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true